### ISSUE TITLE
Sources overview and archive

### ISSUE THREAD

**Issue by PhiSpel** [hbrs-cse/Modellbildung-und-Simulation#158]
- [x] Only check graphics
- [x] Replace [list_of_all_resources.md](https://github.com/joergbrech/Modellbildung-und-Simulation/blob/master/docs/List_of_all_resources.md) with something easier to format
- [x] Generate a full overview over used sources
- [ ] Archive used material as PDFs

**Comment by PhiSpel** [comment]
@LeaKruehler this might be for you?

**Comment by PhiSpel** [comment]
nvm, just delete the file - the sources are linked under each image

**Comment by PhiSpel** [comment]
https://github.com/hbrs-cse/Modellbildung-und-Simulation/blob/c555153d350b6fc88866a72b3ab50e9c947a3193/CONTRIBUTING.md?plain=1#L134
missing source
