### ISSUE TITLE
Document a Style Guide

### ISSUE THREAD

**Issue by joergbrech** [hbrs-cse/Modellbildung-und-Simulation#193]
Add a Markdown-File to this repo with a style guide.

- [x]  Gender: Auf Deutsch mit `:innen`
- [x]  Sprache: Code auf Englisch, Abbildungen und Text Deutsch
- [x]  Grafik-Titel? Abbildungsunterschrift? Wenn Abbildungsunterschrift: Kein Grafik-Titel
- [ ]  Wo kommen Legenden hin?
- [ ] Link Style Guide in Contributing.md or include it
- [x] include or link the [Wiki](https://github.com/joergbrech/Modellbildung-und-Simulation/wiki)
- [x] Add tick box to PR template in [pull_request_template.md](https://github.com/joergbrech/Modellbildung-und-Simulation/blob/master/.github/pull_request_template.md)
- [x] maybe add [Mindmap-Buchprojekt_Livetreffen.pptx](https://github.com/joergbrech/Modellbildung-und-Simulation/files/8088976/Mindmap-Buchprojekt_Livetreffen.pptx)?
- [x] include [Informationen zum Urheberrecht.pdf](https://github.com/joergbrech/Modellbildung-und-Simulation/files/8040574/Informationen.zum.Urheberrecht.pdf) in some way
- [x] Should we abbreviate z.B. and bspw. or not?
- [ ] ...what else?

**Comment by PhiSpel** [comment]
We should also add a guide how to use github. Let's discuss this tomorrow, I am thinking especially about naming/labeling/etc. conventions for issues and PRs.

**Comment by PhiSpel** [comment]
I added 

> Should we abbreviate z.B. and bspw. or not?

, as I was unsure about this

**Comment by LeaKruehler** [comment]
> I added
> 
> > Should we abbreviate z.B. and bspw. or not?
> 
> , as I was unsure about this


We can use the common abbreviation without mentioning their full meanings. There is a guide for "Wissenschaftliches Arbeiten" from Horst Röhrig, where he writes, that common abbreviations can be used just like that without having to write them out first. 
Its on page 14, he also lists common abbrevations on that site. I will include them into the style and writing guide as well. 

[Leitfaden Wissenschaftliches Arbeiten.pdf](https://github.com/joergbrech/Modellbildung-und-Simulation/files/8341908/Leitfaden.Wissenschaftliches.Arbeiten.pdf)

**Comment by LeaKruehler** [comment]
Its not finished at all, but this [https://docs.google.com/document/d/1ibEsHCpuHY3PeX_AvFbtcdYTDdpyqhWJ8UoaVL1uRn0/edit?usp=sharing](url) is the Style Guide

**Comment by LeaKruehler** [comment]
- [ ] remove "file naming conventions" from wiki and include into style guide

**Comment by LeaKruehler** [comment]
I guess its done :)
